### PR TITLE
added lhoff.de

### PR DESCRIPTION
**Pull request by florianeck**
found this domain with suspicious activity on one of my projects...

### CODE REVIEW

**Comment by lisinge** [comment]
Thanks for your PR.
It looks like this domain isn't really a part of a disposable email provider, did you many registrations from this domain?

**Comment by florianeck** [comment]
yes, you are right, i actually have no idea where domain comes from, but somehow i got a lot of suspicious signups from this domain (like 50 within a few minutes from the same ip), i added them to the fork i am using and thought why not adding it here as well...

**Comment by lisinge** [comment]
Yeah this happens to us sometimes to were people with their own domain and probably a catch-all inbox registers hundreds of accounts.

I prefer not to add domains that's actually not a real disposable email provider, i hope you can understand. The good thing is that you don't have to maintain your own fork because you can just add your own blacklist.ymk file to the vendor folder in your rails app as described in this pr here https://github.com/lisinge/valid_email2/pull/5.

Let me know if that solves your problem.

**Comment by florianeck** [comment]
hey thanks, i did not know that, but it totally makes sense. great work on that gem! thanks!

**Comment by lisinge** [comment]
Great! It needs to be documented though. Thanks, but it's a community effort! 😄

**Pull request closed without merging**
