### PR TITLE
Updates disposable_emails.yml

### PR DESCRIPTION
**Pull request by daqua**

### CODE REVIEW

**Comment by lisinge** [comment]
Thanks!

**Comment by softmonkeyjapan** [comment]
Any plan on releasing it soon? Thanks

**Comment by lisinge** [comment]
Sorry @softmonkeyjapan for the delay, i've been out of country with no access to a computer to release from.

I just pushed 1.2.19 to rubygems.

Thanks for the bump!

**Comment by softmonkeyjapan** [comment]
Awesome @lisinge and thank you a lot :)

**Pull request merged**
