### PR TITLE
Make `regex` validator option work

### PR DESCRIPTION
**Pull request by krasnoukhov**
So it's possible to turn it off.

### CODE REVIEW

**Comment by lisinge** [comment]
I'm having trouble understanding what the use case of this is.

In your test case `validates :email, email: { regex: false }` you basically say that you validate the email but then disable all the validations making it a NOP.

So why use the validation at all?

**Comment by krasnoukhov** [comment]
Oh, I should have explained it better. The thing is that I need to validate blacklist/disposable only `on: :create` and I don't want to deal with double errors. Does that make sense?

**Comment by lisinge** [comment]
Alright, i understand.

To be able to even match the blacklist the email has to be somewhat valid (ie. it needs to at least have a domain).

The point of the library is to validate email addresses so i don't really see the point to be able to disable the format validation as that's the first thing you really have to pass to be able to classify it as a real email address.

I understand how you want to use the validation but i don't think it has a real use case other than to not have to deal with the error. So i'm afraid i can't accept this PR.

**Comment by krasnoukhov** [comment]
Ok it's fine. You should consider removing `regex` from `default_options` then because it does not make any sense. Cheers!

**Pull request closed without merging**
