### PR TITLE
Namespace EmailValidator under the ValidEmail2 namespace.

### PR DESCRIPTION
**Pull request by fredngo**
This is a breaking change. The invocation changes from:

```
validates :email, email: true
```

to

```
validates :email, 'valid_email_2/email': true
```

This solves https://github.com/lisinge/valid_email2/issues/46

### CODE REVIEW

**Comment by fredngo** [comment]
All support for Ruby 2.1 has ended, so it (along with 2.0) should probably be removed from the CI checks. Those are the only ones failing.

**Comment by lisinge** [comment]
Hi Fred. Thanks for working on this.

Wow, i had no idea you could namespace validations like this in rails.


I have two problems with this though;

First, as you already pointed out this is a breaking change. This will break peoples code which isn't that bad if we release it as `v2.0`, they'll have to come here on github and find out what changed or i could include a note in the `after_install` message in the gem (which i prefer not to).

It's kinda ugly imo, only because of the name of the gem `'valid_email_2/email': true` is kind of a mouthful. This is only my fault because i had no imagination at all when i named the gem.

One solution that would make it backwards compatible and available explicitly is to include
```ruby
class EmailValidator < ValidEmail2::EmailValidator
end
``` 
in `email_validator.rb`

This still means that we occupy the `email` validator and we are still available through the namespaced `valid_email_2/email` validator.
The best thing would've been if the validator was namespaced from the beginning though.

If people complain that the gem is occupying the `email` validator we could add a deprecation warning this way and eventually phase out the global validator, but i don't feel the need to do this right now.

What do you think?

**Comment by fredngo** [comment]
Hi @lisinge !

I think your inheritance suggestion is a good idea. I'll go ahead and implement that today.

And then it'll be up to you whether to release as a 2.0 or less. I think people upgrading major versions should know that they contain breaking changes, so it's not a big deal IMO.

There is definitely a need for this due to the conflict with Devise... Led to strange behaviors in my own app for sure.

**Comment by lisinge** [comment]
Great work! Thanks for your help!

**Comment by lisinge** [comment]
v2.0.0 is now released with this PR, i also added a deprecation warning with link to upgrade instructions in https://github.com/lisinge/valid_email2/commit/3376119b7e1db3c52cea67e4c0818a55106616f5.

Thanks again!

**Comment by fredngo** [comment]
Yay! Thanks for the release!

**Pull request merged**
